module "eks_cluster" {
  source               = "github.com/apgaua/terraform-modules//eks-cluster"
    # GENERAL SETTINGS
    project_name         = var.project_name
    region               = var.region
    # CLUSTER SETTINGS
    kubernetes_version   = var.kubernetes_version
    zonal_shift        = var.zonal_shift
    upgrade_policy_support_type = var.upgrade_policy_support_type
    auto_scale_options = var.auto_scale_options
    node_instance_type = var.node_instance_type
    # NETWORKING SETTINGS
    ssm_vpc_id         = var.ssm_vpc_id
    ssm_public_subnets = var.ssm_public_subnets
    ssm_private_subnets = var.ssm_private_subnets
    ssm_pod_subnets = var.ssm_pod_subnets
    # DEFAULT TAGS
    default_tags = var.default_tags
}