name: Generate Terraform Diagram with Inframap (Artifact)

on:
  pull_request:
    paths:
      - '**.tf'
      - '**.tfvars'

jobs:
  generate-diagram:
    name: Generate Diagram
    runs-on: ubuntu-latest

    steps:
      # 1. Check out the repository code
      - name: Checkout Code
        uses: actions/checkout@v4

      # 2. Install Terraform CLI
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.0 # Or your desired version

      # 3. Install the standalone Inframap CLI
      - name: Install Inframap
        run: |
          curl -L https://github.com/cycloidio/inframap/releases/download/v0.8.0/inframap-linux-amd64 -o /usr/local/bin/inframap
          chmod +x /usr/local/bin/inframap

      # 4. Install Graphviz. This is required by Inframap to generate images.
      - name: Install Graphviz
        run: sudo apt-get update && sudo apt-get install -y graphviz

      # 5. Initialize Terraform. This is necessary for Inframap to parse
      #    the configuration and its modules.
      #    -backend=false is used because we don't need state for a graph.
      - name: Terraform Init
        run: terraform init -backend=false

      # 6. Generate the diagram as a PNG image using Inframap.
      #    Inframap will automatically detect the output format from the file extension.
      - name: Generate diagram with Inframap
        run: inframap generate . --output-file=terraform-diagram.png

      # 7. Upload the generated diagram as a workflow artifact.
      #    You can find this file in the "Artifacts" section of the
      #    completed workflow run on GitHub.
      - name: Upload Diagram Artifact
        uses: actions/upload-artifact@v4
        with:
          name: terraform-diagram-png
          path: terraform-diagram.png